### ISSUE TITLE
[Feature request] Tailwind 1.4.0 support - new color opacity utilities

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [innocenzi/tailwindcss-theming#21]
After TailwindCSS introduced [new color opacity utilities](https://github.com/tailwindcss/tailwindcss/pull/1627) current approach of opacity and colors generation became not inlined with the official way colors are generated in tailwindCSS.
As a result classes such as `bg-opacity-25`, `text-opacity-25` makes no difference to the opacity level.

@hawezo I actually have mixed feelings about 1.4.0 color utilities and I like how you implemented it - more, but what can we do here? I guess when using tailwind-theming we should still have an access to full list of tailwind features. But what is really great about your approach with colors is that it's fully polyfillable for IE11 and 1.4.0 colors - are not. So maybe let's discuss what is the best thing that should be done here

**Comment by hawezo** [comment]
So, this if fixable with a change on Tailwind's core, but that would be a bit hacky, not sure if Adam would be open to this. I asked him on the Discord and tagged you. 

If it's not possible to do that, the best bet would be to disable Tailwind's `opacity` utilities' implementation.

**Comment by hawezo** [comment]
https://github.com/tailwindcss/tailwindcss/pull/1676#issuecomment-622277441

---

@AndrewBogdanovTSS Answering there, because the PR wasn't the place. 

Normally, that would eventually be polyfillable, since I plan on generating that type of utility:

```css
.text-primary-75 {
  color: rgba(32, 32, 32, var(--text-opacity, 0.75));
}
```

Where `--text-opacity` is used by Tailwind's `opacity` utilities, and `.75` is the default value, defined by the plugin's variant. 

Ran through `postcss-custom-properties`, it gives the following CSS:

```css
.text-primary-75 {
  color: rgba(32, 32, 32, 0.75);
  color: rgba(32, 32, 32, var(--text-opacity, 0.75));
}
```

If I need to use a CSS variable instead of a hard-coded value for some reason, I can have a double fallback which polyfills the same: 

```css
// Generated
.text-primary {
  color: rgba(32, 32, 32, var(--text-opacity, var(--color-primary-opacity-variant, 0.75)));
}

// Polyfilled
.text-primary {
  color: rgba(32, 32, 32, 0.75);
  color: rgba(32, 32, 32, var(--text-opacity, var(--color-primary-opacity-variant, 0.75)));
}
```

Does that answer your concerns?
